from app.core.limits import DEV_API_LIMIT_PER_MONTH

MAX_THUMBNAIL_WIDTH = 2000
MAX_THUMBNAIL_HEIGHT = 2000
MAX_EMBEDDED_WIDTH = 2000
MAX_EMBEDDED_HEIGHT = 2000
MAX_PROJECT_LOGO_WIDTH = 500
MAX_PROJECT_LOGO_HEIGHT = 500
MAX_PROFILE_IMAGE_WIDTH = 1000
MAX_PROFILE_IMAGE_HEIGHT = 1000

API_KEY_LIMIT_PER_MONTH = DEV_API_LIMIT_PER_MONTH
